# This is a basic workflow to help you get started with Actions

name: Print Log when pushed

on:
  push:
    branches: [ master ]

jobs:
  print_log:
    runs-on: ubuntu-latest
    
    steps:

    - name: Run a one-line script
      run: echo Hello, world!
