name: Print Log when manual run

on:
  workflow_dispatch:

jobs:
  print_log:
    runs-on: ubuntu-latest
    
    steps:

    - name: Run a one-line script
      run: echo "Hello! This was done manually."
